### ISSUE TITLE
RE: You and Your Books/Seth

### ISSUE THREAD

**Issue by silver2row** [alexander-g-dean/ESF#5]
Hello,

My name is Seth. This is not an issue really. I just wanted to say thank you for taking time out to supply people w/ knowledge on building around these cores.

Seth

P.S. Thank you! I have about two or three of your books. W/out this repo, I was lacking further investigation. Anyway, thank you again and please keep up the work.

**Comment by alexander-g-dean** [comment]
Thanks so much! I wrote the books and developed the materials to help the
students in my classes learn more easily. It is too easy to drown in the
flood of information available.
Alex

**Comment by silver2row** [comment]
Yes Sir, 

You are right. I hate to admit this idea but I was not familiar w/ this page on github. I could not track down the delay.h and some other files to get cracking on the coding experience to your books.

I am a novice at best right now but I keep drowning in the multitude of ideas revolving around the www.

Anyway, thank you for posting this info. and for addressing the specific chips. 

Seth

P.S. You are right, the flood of info. currently is not actually what I am seeking but every so often, something rings true.

**Comment by alexander-g-dean** [comment]
Thanks - I updated the book description on Amazon to point to the Github
repository to help out others.

Alex
